name: Android CI

on:
  push:
    branches:
      - main
      - tooling-api
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: sparkfabrik/android-build-action@v1.0.0
  with:
    project-path: android
    output-path: my-app.apk
    browserstack-upload: true
    browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
    browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
